/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { FullMathTest } from "../FullMathTest";

export class FullMathTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<FullMathTest> {
    return super.deploy(overrides || {}) as Promise<FullMathTest>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): FullMathTest {
    return super.attach(address) as FullMathTest;
  }
  connect(signer: Signer): FullMathTest__factory {
    return super.connect(signer) as FullMathTest__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FullMathTest {
    return new Contract(address, _abi, signerOrProvider) as FullMathTest;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "z",
        type: "uint256",
      },
    ],
    name: "mulDiv",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "z",
        type: "uint256",
      },
    ],
    name: "mulDivRoundingUp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102af806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80630af8b27f1461003b578063aa9a091214610091575b600080fd5b61007b6004803603606081101561005157600080fd5b810190808035906020019092919080359060200190929190803590602001909291905050506100e7565b6040518082815260200191505060405180910390f35b6100d1600480360360608110156100a757600080fd5b810190808035906020019092919080359060200190929190803590602001909291905050506100fd565b6040518082815260200191505060405180910390f35b60006100f4848484610113565b90509392505050565b600061010a8484846101b0565b90509392505050565b600080841480610130575082848486029250828161012d57fe5b04145b15610153576000821161014257600080fd5b6000828206118282040190506101a9565b61015e8484846101b0565b90506000828061016a57fe5b84860911156101a8577fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff811061019f57600080fd5b80806001019150505b5b9392505050565b600080838502905060008019858709828110838203039150508084116101d557600080fd5b60008114156101ea5783820492505050610272565b8385870982811182039150808303925050600084856000031690508085049450808304925060018182600003040190508082028317925060006002866003021890508086026002038102905080860260020381029050808602600203810290508086026002038102905080860260020381029050808602600203810290508084029450505050505b939250505056fea2646970667358221220dd02287fa7a465a7f2b347dbd31192959c43e569366828eee76fd7d206fbd67564736f6c63430007060033";
