/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DataStorageInterface extends ethers.utils.Interface {
  functions: {
    "WINDOW()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "WINDOW", values?: undefined): string;

  decodeFunctionResult(functionFragment: "WINDOW", data: BytesLike): Result;

  events: {};
}

export class DataStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DataStorageInterface;

  functions: {
    WINDOW(overrides?: CallOverrides): Promise<[number]>;

    "WINDOW()"(overrides?: CallOverrides): Promise<[number]>;
  };

  WINDOW(overrides?: CallOverrides): Promise<number>;

  "WINDOW()"(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    WINDOW(overrides?: CallOverrides): Promise<number>;

    "WINDOW()"(overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    WINDOW(overrides?: CallOverrides): Promise<BigNumber>;

    "WINDOW()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    WINDOW(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "WINDOW()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
