/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IUbeswapPoolPermissionedActionsInterface
  extends ethers.utils.Interface {
  functions: {
    "setCommunityFee(uint8,uint8)": FunctionFragment;
    "setIncentive(address)": FunctionFragment;
    "setLiquidityCooldown(uint32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "setCommunityFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setIncentive",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setLiquidityCooldown",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "setCommunityFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLiquidityCooldown",
    data: BytesLike
  ): Result;

  events: {};
}

export class IUbeswapPoolPermissionedActions extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IUbeswapPoolPermissionedActionsInterface;

  functions: {
    setCommunityFee(
      communityFee0: BigNumberish,
      communityFee1: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setCommunityFee(uint8,uint8)"(
      communityFee0: BigNumberish,
      communityFee1: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setIncentive(
      virtualPoolAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setIncentive(address)"(
      virtualPoolAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setLiquidityCooldown(
      newLiquidityCooldown: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLiquidityCooldown(uint32)"(
      newLiquidityCooldown: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  setCommunityFee(
    communityFee0: BigNumberish,
    communityFee1: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setCommunityFee(uint8,uint8)"(
    communityFee0: BigNumberish,
    communityFee1: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setIncentive(
    virtualPoolAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setIncentive(address)"(
    virtualPoolAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setLiquidityCooldown(
    newLiquidityCooldown: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLiquidityCooldown(uint32)"(
    newLiquidityCooldown: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    setCommunityFee(
      communityFee0: BigNumberish,
      communityFee1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setCommunityFee(uint8,uint8)"(
      communityFee0: BigNumberish,
      communityFee1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setIncentive(
      virtualPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setIncentive(address)"(
      virtualPoolAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setLiquidityCooldown(
      newLiquidityCooldown: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setLiquidityCooldown(uint32)"(
      newLiquidityCooldown: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    setCommunityFee(
      communityFee0: BigNumberish,
      communityFee1: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setCommunityFee(uint8,uint8)"(
      communityFee0: BigNumberish,
      communityFee1: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setIncentive(
      virtualPoolAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setIncentive(address)"(
      virtualPoolAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setLiquidityCooldown(
      newLiquidityCooldown: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLiquidityCooldown(uint32)"(
      newLiquidityCooldown: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setCommunityFee(
      communityFee0: BigNumberish,
      communityFee1: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setCommunityFee(uint8,uint8)"(
      communityFee0: BigNumberish,
      communityFee1: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setIncentive(
      virtualPoolAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setIncentive(address)"(
      virtualPoolAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setLiquidityCooldown(
      newLiquidityCooldown: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLiquidityCooldown(uint32)"(
      newLiquidityCooldown: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
