/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IUbeswapVirtualPoolInterface extends ethers.utils.Interface {
  functions: {
    "cross(int24,bool)": FunctionFragment;
    "increaseCumulative(uint32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "cross",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseCumulative",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "cross", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseCumulative",
    data: BytesLike
  ): Result;

  events: {};
}

export class IUbeswapVirtualPool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IUbeswapVirtualPoolInterface;

  functions: {
    cross(
      nextTick: BigNumberish,
      zeroToOne: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cross(int24,bool)"(
      nextTick: BigNumberish,
      zeroToOne: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    increaseCumulative(
      currentTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increaseCumulative(uint32)"(
      currentTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  cross(
    nextTick: BigNumberish,
    zeroToOne: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cross(int24,bool)"(
    nextTick: BigNumberish,
    zeroToOne: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  increaseCumulative(
    currentTimestamp: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increaseCumulative(uint32)"(
    currentTimestamp: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    cross(
      nextTick: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "cross(int24,bool)"(
      nextTick: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    increaseCumulative(
      currentTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    "increaseCumulative(uint32)"(
      currentTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {};

  estimateGas: {
    cross(
      nextTick: BigNumberish,
      zeroToOne: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cross(int24,bool)"(
      nextTick: BigNumberish,
      zeroToOne: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    increaseCumulative(
      currentTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increaseCumulative(uint32)"(
      currentTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cross(
      nextTick: BigNumberish,
      zeroToOne: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cross(int24,bool)"(
      nextTick: BigNumberish,
      zeroToOne: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    increaseCumulative(
      currentTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increaseCumulative(uint32)"(
      currentTimestamp: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
