/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TickOverflowSafetyEchidnaTestInterface
  extends ethers.utils.Interface {
  functions: {
    "increaseTotalFeeGrowth0Token(uint256)": FunctionFragment;
    "increaseTotalFeeGrowth1Token(uint256)": FunctionFragment;
    "moveToTick(int24)": FunctionFragment;
    "setPosition(int24,int24,int128)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "increaseTotalFeeGrowth0Token",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseTotalFeeGrowth1Token",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moveToTick",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPosition",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "increaseTotalFeeGrowth0Token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseTotalFeeGrowth1Token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moveToTick", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPosition",
    data: BytesLike
  ): Result;

  events: {};
}

export class TickOverflowSafetyEchidnaTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TickOverflowSafetyEchidnaTestInterface;

  functions: {
    increaseTotalFeeGrowth0Token(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increaseTotalFeeGrowth0Token(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    increaseTotalFeeGrowth1Token(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increaseTotalFeeGrowth1Token(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    moveToTick(
      target: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "moveToTick(int24)"(
      target: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setPosition(
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPosition(int24,int24,int128)"(
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  increaseTotalFeeGrowth0Token(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increaseTotalFeeGrowth0Token(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  increaseTotalFeeGrowth1Token(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increaseTotalFeeGrowth1Token(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  moveToTick(
    target: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "moveToTick(int24)"(
    target: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setPosition(
    bottomTick: BigNumberish,
    topTick: BigNumberish,
    liquidityDelta: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPosition(int24,int24,int128)"(
    bottomTick: BigNumberish,
    topTick: BigNumberish,
    liquidityDelta: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    increaseTotalFeeGrowth0Token(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "increaseTotalFeeGrowth0Token(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    increaseTotalFeeGrowth1Token(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "increaseTotalFeeGrowth1Token(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    moveToTick(target: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "moveToTick(int24)"(
      target: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPosition(
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPosition(int24,int24,int128)"(
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    increaseTotalFeeGrowth0Token(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increaseTotalFeeGrowth0Token(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    increaseTotalFeeGrowth1Token(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increaseTotalFeeGrowth1Token(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    moveToTick(target: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "moveToTick(int24)"(
      target: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setPosition(
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPosition(int24,int24,int128)"(
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    increaseTotalFeeGrowth0Token(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increaseTotalFeeGrowth0Token(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    increaseTotalFeeGrowth1Token(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increaseTotalFeeGrowth1Token(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    moveToTick(
      target: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "moveToTick(int24)"(
      target: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setPosition(
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPosition(int24,int24,int128)"(
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
