/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TokenDeltaMathTestInterface extends ethers.utils.Interface {
  functions: {
    "getGasCostOfGetNewPriceAfterInput(uint160,uint128,uint256,bool)": FunctionFragment;
    "getGasCostOfGetNewPriceAfterOutput(uint160,uint128,uint256,bool)": FunctionFragment;
    "getGasCostOfGetToken0Delta(uint160,uint160,uint128,bool)": FunctionFragment;
    "getGasCostOfGetToken1Delta(uint160,uint160,uint128,bool)": FunctionFragment;
    "getNewPriceAfterInput(uint160,uint128,uint256,bool)": FunctionFragment;
    "getNewPriceAfterOutput(uint160,uint128,uint256,bool)": FunctionFragment;
    "getToken0Delta(uint160,uint160,uint128,bool)": FunctionFragment;
    "getToken1Delta(uint160,uint160,uint128,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getGasCostOfGetNewPriceAfterInput",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetNewPriceAfterOutput",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetToken0Delta",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetToken1Delta",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getNewPriceAfterInput",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getNewPriceAfterOutput",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getToken0Delta",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getToken1Delta",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getGasCostOfGetNewPriceAfterInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetNewPriceAfterOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetToken0Delta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetToken1Delta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNewPriceAfterInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNewPriceAfterOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getToken0Delta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getToken1Delta",
    data: BytesLike
  ): Result;

  events: {};
}

export class TokenDeltaMathTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TokenDeltaMathTestInterface;

  functions: {
    getGasCostOfGetNewPriceAfterInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getGasCostOfGetNewPriceAfterInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getGasCostOfGetNewPriceAfterOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getGasCostOfGetNewPriceAfterOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getGasCostOfGetToken0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getGasCostOfGetToken0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getGasCostOfGetToken1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getGasCostOfGetToken1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getNewPriceAfterInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { sqrtQ: BigNumber }>;

    "getNewPriceAfterInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { sqrtQ: BigNumber }>;

    getNewPriceAfterOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { sqrtQ: BigNumber }>;

    "getNewPriceAfterOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { sqrtQ: BigNumber }>;

    getToken0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount0: BigNumber }>;

    "getToken0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount0: BigNumber }>;

    getToken1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount1: BigNumber }>;

    "getToken1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount1: BigNumber }>;
  };

  getGasCostOfGetNewPriceAfterInput(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountIn: BigNumberish,
    zeroToOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getGasCostOfGetNewPriceAfterInput(uint160,uint128,uint256,bool)"(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountIn: BigNumberish,
    zeroToOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getGasCostOfGetNewPriceAfterOutput(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountOut: BigNumberish,
    zeroToOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getGasCostOfGetNewPriceAfterOutput(uint160,uint128,uint256,bool)"(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountOut: BigNumberish,
    zeroToOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getGasCostOfGetToken0Delta(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getGasCostOfGetToken0Delta(uint160,uint160,uint128,bool)"(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getGasCostOfGetToken1Delta(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getGasCostOfGetToken1Delta(uint160,uint160,uint128,bool)"(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getNewPriceAfterInput(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountIn: BigNumberish,
    zeroToOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getNewPriceAfterInput(uint160,uint128,uint256,bool)"(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountIn: BigNumberish,
    zeroToOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getNewPriceAfterOutput(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountOut: BigNumberish,
    zeroToOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getNewPriceAfterOutput(uint160,uint128,uint256,bool)"(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountOut: BigNumberish,
    zeroToOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getToken0Delta(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getToken0Delta(uint160,uint160,uint128,bool)"(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getToken1Delta(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getToken1Delta(uint160,uint160,uint128,bool)"(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getGasCostOfGetNewPriceAfterInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetNewPriceAfterInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetNewPriceAfterOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetNewPriceAfterOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetToken0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetToken0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetToken1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetToken1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNewPriceAfterInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNewPriceAfterInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNewPriceAfterOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNewPriceAfterOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getToken0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getToken0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getToken1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getToken1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getGasCostOfGetNewPriceAfterInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetNewPriceAfterInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetNewPriceAfterOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetNewPriceAfterOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetToken0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetToken0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetToken1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetToken1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNewPriceAfterInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNewPriceAfterInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNewPriceAfterOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNewPriceAfterOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getToken0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getToken0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getToken1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getToken1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getGasCostOfGetNewPriceAfterInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGasCostOfGetNewPriceAfterInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGasCostOfGetNewPriceAfterOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGasCostOfGetNewPriceAfterOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGasCostOfGetToken0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGasCostOfGetToken0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGasCostOfGetToken1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGasCostOfGetToken1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNewPriceAfterInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNewPriceAfterInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNewPriceAfterOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNewPriceAfterOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroToOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getToken0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getToken0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getToken1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getToken1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
